### ISSUE TITLE
Redis store is not supported on Docker image siddhiio/siddhi-tooling:5.1.2

### ISSUE THREAD

**Issue by xtrmstep** [wso2-extensions/siddhi-store-redis#31]
Hi,

Siddhi tooling suggest option to create redis store, but then it throws an error:

```
ERROR {io.siddhi.distribution.editor.core.internal.DebugRuntime} - Siddhi App 'SiddhiApp' is in faulty state. (Encoded) 
io.siddhi.core.exception.SiddhiAppCreationException: Error on 'SiddhiApp' @ Line: 7. Position: 29, near '@store(type = 'redis', cluster.mode = "false", nodes = "localhost:6379@root", ttl.seconds = "30", ttl.on.update = "true", ttl.on.read = "true")
@primaryKey('d' )
define table fghfh (d string)'. redis/clients/jedis/exceptions/JedisDataException
	at io.siddhi.core.util.ExceptionUtil.populateQueryContext(ExceptionUtil.java:43)
	at io.siddhi.core.util.parser.SiddhiAppParser.defineTableDefinitions(SiddhiAppParser.java:404)
	at io.siddhi.core.util.parser.SiddhiAppParser.parse(SiddhiAppParser.java:231)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:85)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:95)
	at io.siddhi.distribution.editor.core.internal.DebugRuntime.createRuntime(DebugRuntime.java:201)
	at io.siddhi.distribution.editor.core.internal.DebugRuntime.(DebugRuntime.java:56)
	at io.siddhi.distribution.editor.core.internal.DebugProcessorService.start(DebugProcessorService.java:38)
	at io.siddhi.distribution.editor.core.internal.EditorMicroservice.start(EditorMicroservice.java:761)
	at io.siddhi.distribution.editor.core.internal.EditorMicroservice.startWithVariables(EditorMicroservice.java:781)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$58(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: redis/clients/jedis/exceptions/JedisDataException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at io.siddhi.core.util.SiddhiClassLoader.loadClass(SiddhiClassLoader.java:32)
	at io.siddhi.core.util.SiddhiClassLoader.loadExtensionImplementation(SiddhiClassLoader.java:48)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addTable(DefinitionParserHelper.java:206)
	at io.siddhi.core.util.SiddhiAppRuntimeBuilder.defineTable(SiddhiAppRuntimeBuilder.java:129)
	at io.siddhi.core.util.parser.SiddhiAppParser.defineTableDefinitions(SiddhiAppParser.java:402)
	... 19 more
Caused by: java.lang.ClassNotFoundException: redis.clients.jedis.exceptions.JedisDataException cannot be found by siddhi-store-redis_3.1.1
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:448)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:361)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:353)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 28 more
```
The code is dumb simple:

```
@App:name('SiddhiApp')

@App:description('Description of the plan')
@store(type = 'redis', cluster.mode = "false", nodes = "localhost:6379@root", ttl.seconds = "30", ttl.on.update = "true", ttl.on.read = "true")
@primaryKey('d' )
define table fghfh (d string);
```

I'v tried to download JAR [jedis-2.9.0.jar](https://mvnrepository.com/artifact/redis.clients/jedis/2.9.0) and put to jar folder as suggested for installing extentions, but it didn't work. The error still the same.

**Comment by AnuGayan** [comment]
@xtrmstep Please try coping Jedis jar to bundles folder, because  jedis-2.9.0.jar is already bundled jar.

**Comment by xtrmstep** [comment]
@AnuGayan thanks. It works now.
